"""test

Revision ID: 025db36aa331
Revises: 4dd68526e410
Create Date: 2022-05-23 03:47:22.711312

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '025db36aa331'
down_revision = '4dd68526e410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('isArtist', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
