"""Adding to users table columns related to payments

Revision ID: 076151405c70
Revises: 4b6d549c2015
Create Date: 2022-07-02 19:23:50.406025

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '076151405c70'
down_revision = '4b6d549c2015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('privateKey', sa.String(), nullable=True))
    op.add_column('users', sa.Column('publicKey', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'publicKey')
    op.drop_column('users', 'privateKey')
    # ### end Alembic commands ###
