"""add more fields to table users - nullable true

Revision ID: 17e3f9e05b6b
Revises: 97a6568f8d03
Create Date: 2022-05-15 00:24:47.839979

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '17e3f9e05b6b'
down_revision = '97a6568f8d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', postgresql.BYTEA(), nullable=True))
    op.add_column('users', sa.Column('isPremium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('isArtist', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    op.drop_column('users', 'isPremium')
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
