"""test2

Revision ID: 2d857f24ef7e
Revises: 025db36aa331
Create Date: 2022-05-23 03:48:33.756376

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '2d857f24ef7e'
down_revision = '025db36aa331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isArtist', sa.Boolean(), nullable=False))
    op.alter_column('users', 'isArtist', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    # ### end Alembic commands ###
