"""add more fields to table users

Revision ID: 3900c5168f6f
Revises: c5171defed85
Create Date: 2022-05-15 00:45:11.962576

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '3900c5168f6f'
down_revision = 'c5171defed85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', postgresql.BYTEA(), nullable=True))
    op.add_column('users', sa.Column('isPremium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isArtist', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    op.drop_column('users', 'isPremium')
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
