"""Adding profileImage column

Revision ID: 39d78dfd08ea
Revises: f3820a15ddcd
Create Date: 2022-06-06 22:34:12.340439

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '39d78dfd08ea'
down_revision = 'f3820a15ddcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
