"""trying to add users table

Revision ID: 40739a580bac
Revises: 82ff255c5e1e
Create Date: 2022-04-23 22:58:31.399354

"""
# import sqlalchemy as sa

# from alembic import op

# revision identifiers, used by Alembic.
revision = '40739a580bac'
down_revision = '82ff255c5e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
