"""trying to add users table

Revision ID: 4239d87582b1
Revises: 40739a580bac
Create Date: 2022-04-23 23:12:45.630010

"""
# import sqlalchemy as sa

# from alembic import op

# revision identifiers, used by Alembic.
revision = '4239d87582b1'
down_revision = '40739a580bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
