"""Update users table with followings and followers columns

Revision ID: 4b6d549c2015
Revises: 39d78dfd08ea
Create Date: 2022-06-21 03:00:03.208281

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4b6d549c2015'
down_revision = '39d78dfd08ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('following', sa.ARRAY(sa.Integer()), nullable=True)
    )
    op.add_column(
        'users', sa.Column('followers', sa.ARRAY(sa.Integer()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'followers')
    op.drop_column('users', 'following')
    # ### end Alembic commands ###
