"""New Migration

Revision ID: 4cf82bb1d0b9
Revises: dc9f70c57e76
Create Date: 2022-05-16 00:12:48.652418

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '4cf82bb1d0b9'
down_revision = 'dc9f70c57e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dateCreated', sa.DateTime(), nullable=True))
    op.add_column(
        'users', sa.Column('dateUpdated', sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index('ix_users_firstName', table_name='users')
    op.drop_index('ix_users_lastName', table_name='users')
    op.drop_column('users', 'profileImage')
    op.drop_column('users', 'dateCreate')
    op.drop_column('users', 'time_updated')
    op.drop_column('users', 'isArtist')
    op.drop_column('users', 'isPremium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('isPremium', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'users',
        sa.Column('isArtist', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'users',
        sa.Column(
            'time_updated',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'users',
        sa.Column(
            'dateCreate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'users',
        sa.Column(
            'profileImage', postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.create_index('ix_users_lastName', 'users', ['lastName'], unique=False)
    op.create_index('ix_users_firstName', 'users', ['firstName'], unique=False)
    op.drop_column('users', 'dateUpdated')
    op.drop_column('users', 'dateCreated')
    # ### end Alembic commands ###
