"""Update user table attributes

Revision ID: 5e3a2feaa75d
Revises: 0a69d1546a68
Create Date: 2022-05-13 03:03:59.036819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3a2feaa75d'
down_revision = '0a69d1546a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_firstName', table_name='users')
    op.drop_index('ix_users_lastName', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_lastName', 'users', ['lastName'], unique=False)
    op.create_index('ix_users_firstName', 'users', ['firstName'], unique=False)
    # ### end Alembic commands ###
