"""New Migration

Revision ID: 676a8aa0c124
Revises:
Create Date: 2022-05-14 02:21:56.747274

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '676a8aa0c124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
