"""test6

Revision ID: 77359ff8bb19
Revises: 7b3bb05bbd28
Create Date: 2022-05-23 20:24:32.912814

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '77359ff8bb19'
down_revision = '7b3bb05bbd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('isArtist', sa.Boolean(), server_default='False', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    # ### end Alembic commands ###
