"""test5

Revision ID: 7b3bb05bbd28
Revises: 8165ffabf0f2
Create Date: 2022-05-23 20:23:46.528637

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7b3bb05bbd28'
down_revision = '8165ffabf0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isArtist', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    # ### end Alembic commands ###
