"""Update users table with transactionHash columns

Revision ID: 7f04299c7138
Revises: 076151405c70
Create Date: 2022-07-02 19:40:17.201660

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '7f04299c7138'
down_revision = '076151405c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transactionHash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transactionHash')
    # ### end Alembic commands ###
