"""Adding token notification to users table

Revision ID: 91e939ad2ca8
Revises: 7f04299c7138
Create Date: 2022-07-07 16:17:14.966239

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '91e939ad2ca8'
down_revision = '7f04299c7138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tokenNotification', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tokenNotification')
    # ### end Alembic commands ###
