"""add more fields to table users

Revision ID: 97a6568f8d03
Revises: ad8013ff9aa2
Create Date: 2022-05-15 00:13:08.394368

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '97a6568f8d03'
down_revision = 'ad8013ff9aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', postgresql.BYTEA(), nullable=True))
    op.add_column('users', sa.Column('isPremium', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('isArtist', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    op.drop_column('users', 'isPremium')
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
