"""add table user

Revision ID: ad8013ff9aa2
Revises:
Create Date: 2022-05-14 03:26:11.211768

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ad8013ff9aa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('firstName', sa.String(), nullable=True),
        sa.Column('lastName', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phoneNumber', sa.String(), nullable=True),
        sa.Column('dateCreate', sa.DateTime(), nullable=True),
        sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_index(
        op.f('ix_users_phoneNumber'), 'users', ['phoneNumber'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phoneNumber'), table_name='users')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
