"""remove extra fields

Revision ID: c5171defed85
Revises: 17e3f9e05b6b
Create Date: 2022-05-15 00:35:28.213429

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c5171defed85'
down_revision = '17e3f9e05b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    op.drop_column('users', 'profileImage')
    op.drop_column('users', 'isPremium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('isPremium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'users',
        sa.Column(
            'profileImage', postgresql.BYTEA(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'users', sa.Column('isArtist', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
