"""Adding username, location and bio as a column

Revision ID: c782c9880d64
Revises: b259157eae1f
Create Date: 2022-05-27 01:18:07.887255

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c782c9880d64'
down_revision = 'b259157eae1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('biography', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biography')
    op.drop_column('users', 'location')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
