"""Adding Token table

Revision ID: c933d1bd6d3d
Revises: aae60af8b786
Create Date: 2022-05-12 03:34:43.707449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c933d1bd6d3d'
down_revision = 'aae60af8b786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
