"""trying to add users table

Revision ID: e43db0de5757
Revises: 4239d87582b1
Create Date: 2022-04-23 23:18:57.235910

"""
# import sqlalchemy as sa

# from alembic import op

# revision identifiers, used by Alembic.
revision = 'e43db0de5757'
down_revision = '4239d87582b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
