"""Deleting profileImage column temporarily

Revision ID: f3820a15ddcd
Revises: 4889e0f01a94
Create Date: 2022-06-06 22:32:56.539268

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'f3820a15ddcd'
down_revision = '4889e0f01a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('profileImage', sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
