"""test3

Revision ID: fbe570c5def2
Revises: 2d857f24ef7e
Create Date: 2022-05-23 03:51:46.426933

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'fbe570c5def2'
down_revision = '2d857f24ef7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('isArtist', sa.Boolean(), server_default='False', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isArtist')
    # ### end Alembic commands ###
